### PR TITLE
Upgraded to work with Django 4.0

### PR DESCRIPTION
**Pull request by jsayles**
As of Django 3.0 `urlunquote_plus` was deprecated in favour of `urllib.parse.unquote_plus` and as of 4.0 the old method was removed.  This change and updating `urls.py` to use `django.urls.path` was all that was needed to get this code working under Django 4.0.  I also merged all the open dependabot branches while I was at it.

### CODE REVIEW

**Comment by dtcooper** [comment]
Using this with success! +1

**Comment by jsayles** [comment]
Tests fail on Python2 which is no longer supported.

**Comment by dtcooper** [comment]
@bradleyg Any update on whether this can be merged & released to support Django 4.0?

**Comment by bradleyg** [comment]
thanks!

**Comment by bradleyg** [comment]
Thanks!

**Pull request merged**
