### PR TITLE
Added Mumbai Region

### PR DESCRIPTION
**Pull request by rmad17**
Added endpoint for Mumbai Region(ap-south-1)
Endpoint as mentioned here http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

### CODE REVIEW

**Comment by bradleyg** [comment]
Thanks, this is  fixed in 6b6e47ac00b26d73838e7dea7c162b52a5a38710

**Comment by rmad17** [comment]
Oh, I didn't realise that. However it did not work for me when I had the bucket region as Mumbai.

**Comment by bradleyg** [comment]
I've only just committed the fix, can you try again?

**Comment by rmad17** [comment]
Oh great. I have since moved on from this library though even though I liked it. I had to upload to S3 after form submission with a lot of customization. I couldn't do it with this.

**Pull request closed without merging**
